tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
tap "railwaycat/emacsmacport"

brew "aspell"
brew "coreutils"
brew "ghostscript"
brew "git"
brew "git-lfs"
brew "python@3.8"
brew "librsvg"
brew "imagemagick"
brew "ispell"
brew "leiningen"
brew "node"
brew "jq"
brew "ripgrep"
brew "the_silver_searcher"

cask "dropbox"
cask "firefox"
cask "google-chrome"
cask "google-cloud-sdk"
cask "iterm2"
cask "intellij-idea"
cask "rectangle"
cask "spotify"
cask "mactex"
cask "slack"
cask "karabiner-elements"
cask "licecap"
cask "steam"
cask "zoom"
cask "vlc"
# cask "ultimaker-cura"
cask "uhk-agent"
cask "minecraft"
cask "discord"
cask "emacs-mac"
# cask "adobe-creative-cloud"
